PierresSassyStore/Models/Flavor.cs
using System.ComponentModel.DataAnnotations;
using System.Collections.Generic;
namespace PierresSassyStore.Models
{
    public class Flavor
    {
        public int FlavorId { get; set; }
        [Required]
        public string Name { get; set; }
        [Required]
        public string Description { get; set; }
        public bool IsSeasonal { get; set; }
        [Display(Name = "Season Available")]
        public string AvailableSeason { get; set; }
        public bool IsAvailable { get; set; }
        public ICollection<FlavorTreat> Treats { get; set; }
        public string Image_url { get; set; }

        public Flavor()
        {
            this.Treats = new HashSet<FlavorTreat>();
        }
    }
}

PierresSassyStore/ViewModels/Flavors/DetailsViewModel.cs
using PierresSassyStore.Models;
using System.Collections.Generic;

namespace PierresSassyStore.ViewModels
{
    public class FlavorsDetailsViewModel
    {
        public Flavor Flavor { get; set; }
        public List<Treat> AllTreats { get; set; }
    }
}

PierresSassyStore/ViewModels/Treats/DetailsViewModel.cs
using PierresSassyStore.Models;
using System.Collections.Generic;

namespace PierresSassyStore.ViewModels
{
    public class TreatsDetailsViewModel
    {
        public Treat Treat { get; set; }
        public List<Flavor> AllFlavors { get; set; }
    }
}

PierresSassyStore/Controllers/FlavorsController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Authorization;
using System.Security.Claims;
using PierresSassyStore.Models;
using Microsoft.EntityFrameworkCore;
using System.Threading.Tasks;
using System;
using System.Linq;
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc.Rendering;
using PierresSassyStore.ViewModels;

namespace PierresSassyStore.Controllers
{
    public class FlavorsController : Controller
    {
        private readonly PierresSassyStoreContext _db;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly SignInManager<ApplicationUser> _signInManager;

        public FlavorsController(UserManager<ApplicationUser> userManager, SignInManager<ApplicationUser> signInManager, PierresSassyStoreContext db)
        {
            _userManager = userManager;
            _signInManager = signInManager;
            _db = db;
        }

        public ActionResult Index()
        {
            List<Flavor> model = _db.Flavors.ToList();
            return View(model);
        }

        [Authorize]
        public ActionResult Create()
        {
            ViewBag.TreatIds = new SelectList(_db.Treats.ToList(), "TreatId", "Name");
            return View();
        }

        [Authorize]
        [HttpPost]
        public ActionResult Create(Flavor flavor, int TreatIds)
        {
            _db.Flavors.Add(flavor);
            if (TreatIds != 0)
            {
                _db.FlavorTreats.Add(new FlavorTreat() { FlavorId = flavor.FlavorId, TreatId = TreatIds });
            }
            _db.SaveChanges();
            return RedirectToAction("Index");
        }

        [Authorize]
        public ActionResult Edit(int id)
        {
            Flavor model = _db.Flavors.FirstOrDefault(t => t.FlavorId == id);
            return View(model);
        }

        [Authorize]
        [HttpPost]
        public ActionResult Edit(Flavor flavor)
        {
            _db.Entry(flavor).State = EntityState.Modified;
            _db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult Details(int id)
        {
            Flavor thisFlavor = _db.Flavors.Include(f => f.Treats).ThenInclude(ft => ft.Treat).FirstOrDefault(t => t.FlavorId == id);
            List<Treat> treats = _db.Treats.ToList();
            return View(new FlavorsDetailsViewModel() { Flavor = thisFlavor, AllTreats = treats });
        }

        [Authorize]
        [HttpPost, ActionName("Details")]
        public ActionResult UpdateFlavors(List<int> Treats, int FlavorId)
        {
            List<FlavorTreat> thisTreatFlavors = _db.FlavorTreats.Where(ft => ft.FlavorId == FlavorId).ToList();
            List<int> treatIds = thisTreatFlavors.Select(ft => ft.TreatId).ToList();
            foreach (int treatId in treatIds)
            {
                if (!Treats.Contains(treatId))
                {
                    var join = thisTreatFlavors.FirstOrDefault(tf => tf.TreatId == treatId);
                    _db.FlavorTreats.Remove(join);
                }
            }
            foreach (int newTreatId in Treats)
            {
                if (!treatIds.Contains(newTreatId))
                {
                    var join = new FlavorTreat() { TreatId = newTreatId, FlavorId = FlavorId };
                    _db.FlavorTreats.Add(join);
                }
            }
            _db.SaveChanges();

            return RedirectToAction("Details");
        }

        [Authorize]
        [HttpPost]
        public ActionResult Delete(int id)
        {
            Flavor thisFlavor = _db.Flavors.FirstOrDefault(t => t.FlavorId == id);
            _db.Flavors.Remove(thisFlavor);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

PierresSassyStore/Controllers/TreatsController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Authorization;
using System.Security.Claims;
using PierresSassyStore.Models;
using Microsoft.EntityFrameworkCore;
using System.Threading.Tasks;
using System;
using System.Linq;
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc.Rendering;
using PierresSassyStore.ViewModels;

namespace PierresSassyStore.Controllers
{
    public class TreatsController : Controller
    {
        private readonly PierresSassyStoreContext _db;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly SignInManager<ApplicationUser> _signInManager;

        public TreatsController(UserManager<ApplicationUser> userManager, SignInManager<ApplicationUser> signInManager, PierresSassyStoreContext db)
        {
            _userManager = userManager;
            _signInManager = signInManager;
            _db = db;
        }

        public ActionResult Index()
        {
            List<Treat> model = _db.Treats.ToList();
            return View(model);
        }

        [Authorize]
        public ActionResult Create()
        {
            ViewBag.FlavorIds = new SelectList(_db.Flavors.ToList(), "FlavorId", "Name");
            return View();
        }

        [Authorize]
        [HttpPost]
        public ActionResult Create(Treat treat, int FlavorIds)
        {
            _db.Treats.Add(treat);
            if(FlavorIds != 0)
            {
                _db.FlavorTreats.Add(new FlavorTreat(){TreatId = treat.TreatId, FlavorId = FlavorIds });
            }
            _db.SaveChanges();
            return RedirectToAction("Index");
        }

        [Authorize]
        public ActionResult Edit(int id)
        {
            Treat model = _db.Treats.FirstOrDefault(t => t.TreatId == id);
            ViewBag.FlavorIds = new SelectList(_db.Flavors.ToList(), "FlavorId", "Name");
            return View(model);
        }

        [Authorize]
        [HttpPost]
        public ActionResult Edit(Treat treat, int FlavorId)
        {
            if (FlavorId != 0)
            {
                _db.FlavorTreats.Add(new FlavorTreat() { TreatId = treat.TreatId, FlavorId = FlavorId });
            }
            _db.Entry(treat).State = EntityState.Modified;
            _db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult Details(int id)
        {
            Treat thisTreat = _db.Treats.Include(t => t.Flavors).ThenInclude(ft => ft.Flavor).FirstOrDefault(t => t.TreatId == id);
            List<Flavor> flavors = _db.Flavors.ToList();
            return View(new TreatsDetailsViewModel(){Treat = thisTreat, AllFlavors = flavors});
        }

        [Authorize]
        [HttpPost, ActionName("Details")]
        public ActionResult UpdateFlavors(List<int> Flavors, int TreatId)
        {
            List<FlavorTreat> thisTreatFlavors = _db.FlavorTreats.Where(ft => ft.TreatId == TreatId).ToList();
            List<int> flavorIds = thisTreatFlavors.Select(ft => ft.FlavorId).ToList();
            foreach(int flavId in flavorIds)
            {
                if(!Flavors.Contains(flavId))
                {
                    var join = thisTreatFlavors.FirstOrDefault(tf => tf.FlavorId == flavId);
                    _db.FlavorTreats.Remove(join);
                }
            }
            foreach(int newFlavId in Flavors)
            {
                if (!flavorIds.Contains(newFlavId))
                {
                    var join = new FlavorTreat(){TreatId = TreatId, FlavorId = newFlavId };
                    _db.FlavorTreats.Add(join);
                }
            }
            _db.SaveChanges();

            return RedirectToAction("Details");
        }

        [Authorize]
        [HttpPost]
        public ActionResult Delete(int id)
        {
            Treat thisTreat = _db.Treats.FirstOrDefault(t => t.TreatId == id);
            _db.Treats.Remove(thisTreat);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

PierresSassyStore/Views/Flavors/Create.cshtml
@model PierresSassyStore.Models.Flavor
@{
    ViewData["AvailableSeason"] =  new SelectList(
        new List<SelectListItem>
        {
            new SelectListItem { Selected = true, Text = "All", Value = "All"},
            new SelectListItem { Selected = false, Text = "Winter", Value = "Winter"},
            new SelectListItem { Selected = false, Text = "Spring", Value = "Spring"},
            new SelectListItem { Selected = false, Text = "Fall", Value = "Fall"},
            new SelectListItem { Selected = false, Text = "Summer", Value = "Summer"},
            new SelectListItem { Selected = false, Text = "New Year", Value = "New Year"},
            new SelectListItem { Selected = false, Text = "Valentine's Day", Value = "Valentine's Day"},
            new SelectListItem { Selected = false, Text = "St. Patrick's Day", Value = "St. Patrick's Day"},
            new SelectListItem { Selected = false, Text = "Easter", Value = "Easter"},
            new SelectListItem { Selected = false, Text = "4th of July", Value = "4th of July"},
            new SelectListItem { Selected = false, Text = "Halloween", Value = "Halloween"},
            new SelectListItem { Selected = false, Text = "Thanksgiving", Value = "Thanksgiving"},
            new SelectListItem { Selected = false, Text = "Christmas", Value = "Christmas"},
        }, "Value" , "Text", 1);
}

<h2>Add a flavor to the library!</h2>

@using (Html.BeginForm())
{
    <div class="form-group">
        @Html.LabelFor(m => m.Name)
        @Html.TextBoxFor(m => m.Name)
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Description)
        @Html.TextBoxFor(m => m.Description)
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.IsSeasonal)
        @Html.CheckBoxFor(m => m.IsSeasonal)
    </div>
    <div class="form-group">
        @Html.Label("Select Most Applicable Season / Holiday")
        @Html.DropDownList("AvailableSeason")
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.IsAvailable)
        @Html.CheckBoxFor(m => m.IsAvailable)
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Image_url)
        @Html.TextBoxFor(m => m.Image_url)
    </div>
    <div class="form-group">
        @Html.Label("Select A Treat to use this Flavor")
        @Html.DropDownList("TreatIds")
    </div>

    <input type="submit" value="Add new Flavor">
}

PierresSassyStore/Views/Flavors/Details.cshtml
@model PierresSassyStore.ViewModels.FlavorsDetailsViewModel
@using PierresSassyStore.ViewModels
@section Scripts
{
    <script type="text/javascript">
        function DisplayTreats(){
            $("#treatOptions").toggle();
        }
        $(document).ready(function(){
            $("#treatOptions").hide();
        });
    </script>
}

<h1>@Model.Flavor.Name</h1>

@if(string.IsNullOrEmpty(Model.Flavor.Image_url))
{
    <img src="~/img/genericFlavors.jpg" class="detail-img" alt="Display of Generic Flavors">
}
else
{
    <img src="@Model.Flavor.Image_url" class="detail-img" alt="Display Image, @Model.Flavor.Name">
}
<h3>About this Flavor:</h3>
<ul>
    @if(Model.Flavor.IsSeasonal || Model.Flavor.AvailableSeason != "All")
    {
        <li>@Model.Flavor.Name is seasonal - most often available around @Model.Flavor.AvailableSeason</li>
    }
    else{
        <li>@Model.Flavor.Name is available year-round</li>
    }
    <li>It is currently @(Model.Flavor.IsAvailable ? "" : "not ") available in stores</li>
</ul>

@if(Model.Flavor.Treats.Count == 0)
{
    <h4>This flavor isn't used on any treats!</h4>
}
else
{
    <h4>Treats this Flavor is used on</h4>
    
    <ul>
    @foreach(FlavorTreat ft in Model.Flavor.Treats)
    {
        <li>@ft.Treat.Name | @ft.Treat.Description | @Html.ActionLink("Learn More", "Details", "Treats", new { id = @ft.Treat.TreatId})</li>
    }
    </ul>
}
<p>@Html.ActionLink("Go back to Flavors List", "Index", "Flavors")</p>
<p>@Html.ActionLink("Go to Treats List", "Index", "Treats")</p>
@if(User.Identity.IsAuthenticated)
{
     <div class="Admin">
        <h4>Administrative Tools</h4>
        <p><button type="click" class="btn btn-primary" onclick="DisplayTreats()">Update the treats this flavor is used on!</button></p>
        <p>@Html.ActionLink("Edit", "Edit", new { id = @Model.Flavor.FlavorId }, new {@class = "btn btn-primary"})
        @await Html.PartialAsync("_AreYouSurePartial", new ModalViewModel(){ Name = "Remove", LinkAction="Delete", LinkController = "Flavors", Id = @Model.Flavor.FlavorId })</p>
        <div id="treatOptions">
            <h6>Treat Options</h6>
            @if(Model.AllTreats.Count == 0)
            {
                <p>There are no treats to use this with at this time</p>
                @Html.ActionLink("Add one here!", "Create", "Treats")
            }
            else
            {
                @using(Html.BeginForm())
                {
                    @Html.Hidden("FlavorId", Model.Flavor.FlavorId)
                    @foreach(Treat treat in Model.AllTreats)
                    {
                        <div class="form-group">
                            @Html.Label(@treat.Name)
                            @if(Model.Flavor.Treats.FirstOrDefault(f => f.Treat.TreatId == treat.TreatId) != null)
                            {
                                <input type="checkbox" name="Treats" value="@treat.TreatId" checked>
                            }
                            else
                            {
                                <input type="checkbox" name="Treats" value="@treat.TreatId">
                            }
                        </div>
                    }
                    <input type="submit" value="Update Treats">
                }
            }
        </div>
    </div>
}

PierresSassyStore/Views/Flavors/Edit.cshtml
@model PierresSassyStore.Models.Flavor
@{
    ViewData["AvailableSeason"] =  new SelectList(
        new List<SelectListItem>
        {
            new SelectListItem { Selected = true, Text = "All", Value = "All"},
            new SelectListItem { Selected = false, Text = "Winter", Value = "Winter"},
            new SelectListItem { Selected = false, Text = "Spring", Value = "Spring"},
            new SelectListItem { Selected = false, Text = "Fall", Value = "Fall"},
            new SelectListItem { Selected = false, Text = "Summer", Value = "Summer"},
            new SelectListItem { Selected = false, Text = "New Year", Value = "New Year"},
            new SelectListItem { Selected = false, Text = "Valentine's Day", Value = "Valentine's Day"},
            new SelectListItem { Selected = false, Text = "St. Patrick's Day", Value = "St. Patrick's Day"},
            new SelectListItem { Selected = false, Text = "Easter", Value = "Easter"},
            new SelectListItem { Selected = false, Text = "4th of July", Value = "4th of July"},
            new SelectListItem { Selected = false, Text = "Halloween", Value = "Halloween"},
            new SelectListItem { Selected = false, Text = "Thanksgiving", Value = "Thanksgiving"},
            new SelectListItem { Selected = false, Text = "Christmas", Value = "Christmas"},
        }, "Value" , "Text", 1);
}

<h2>Update @Model.Name!</h2>

@using (Html.BeginForm())
{
    @Html.HiddenFor(m => m.FlavorId)
    <div class="form-group">
        @Html.LabelFor(m => m.Name)
        @Html.TextBoxFor(m => m.Name)
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Description)
        @Html.TextBoxFor(m => m.Description)
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.IsSeasonal)
        @Html.CheckBoxFor(m => m.IsSeasonal)
    </div>
    <div class="form-group">
        @Html.Label("Select Most Applicable Season / Holiday")
        @Html.DropDownList("AvailableSeason")
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.IsAvailable)
        @Html.CheckBoxFor(m => m.IsAvailable)
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Image_url)
        @Html.TextBoxFor(m => m.Image_url)
    </div>

    <input type="submit" value="Update Flavor">
}

PierresSassyStore/Views/Flavors/Index.cshtml
@using System.Collections.Generic
@model List<PierresSassyStore.Models.Flavor>
<h1>Flavor Library</h1>
@if(User.Identity.IsAuthenticated)
{
    <h4>Add a new flavor @Html.ActionLink("here","Create")</h4>
}

@if(Model.Count == 0)
{
    <h3>There are no flavor modifiers in the library</h3>
}
else
{
    <ul class="library">
        @foreach(Flavor flavor in Model)
        {
            <li>
                @await Html.PartialAsync("_CardPartial", flavor)
            </li>
        }
    </ul>
}
<p>@Html.ActionLink("Go to Treats List", "Index", "Treats")</p>